// Generated by https://quicktype.io
// Extension pasteJSONasCode 
// Copy JSON en postman, en VSC ctrl+shift+p extension parse Json as Code y luego nombre PokemonListResponse y ya genera este código.

export interface PokemonListResponse {
    count:     number;
    next:      string;
    previous?: string;
    results:   SmallPokemon[];
}

export interface SmallPokemon {
    name:   string;
    url:    string;
    id:     number;
    img:    string;
    
}

